name = "abstract-realms"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "ABSTRACT_REALMS_DB"
database_name = "abstract-realms-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
